### ISSUE TITLE
ProgressBar (maybe) prevents garbage collection

### ISSUE THREAD

**Issue by taketwo** [dnouri/skorch#306] opened 2018-08-07 01:02 UTC
I started to use the `ProgressBar` callback today and noticed that it affects GPU memory consumption of my program.

Specifically, without this callback, `nvidia-smi` consistently reports `4247MiB` usage by my program. After adding the progress bar, consumption starts from the same number, but then steadily increases throughout the first epoch, eventually peaking around `7500MiB`, and does not change anymore in subsequent epochs. I could reproduce this behavior in every run. I also tried to run with different batch sizes. The absolute numbers change, e.g. for half the batch it's `2502MiB` and `4182MiB`, but it's still a huge overhead.

Looking at the callback code, I don't see any reason for this behavior. Perhaps the console IO somehow prevents garbage collection? No idea.

Most likely this is not a skorch issue. Nevertheless, I think it would be great if we can confirm this, and maybe add a warning to the callback documentation.

**Comment by benjamin-work** [comment] 2018-08-07 07:57
This is a strange issue, I also can't find any offending line of code. Could you post a (minimal) code example to reproduce the issue? Does it depend on using jupyter notebook?

Maybe you could add a callback that calls [empty_cache](https://pytorch.org/docs/stable/cuda.html#torch.cuda.empty_cache) at the end of each epoch and check if the leak persists. [Here](https://pytorch.org/docs/stable/notes/cuda.html#cuda-memory-management) is more on memory management.

> Most likely this is not a skorch issue. Nevertheless, I think it would be great if we can confirm this, and maybe add a warning to the callback documentation.

If this is reproducible behavior, it should be fixed somewhere, just warning the user that twice as much GPU memory is needed for a progress bar is not acceptable ;)

**Comment by taketwo** [comment] 2018-08-07 13:31
Here is a minimal example I've come up with:

```python
#!/usr/bin/env python
# -*- coding: utf-8 -*-

import skorch
import torch
import torch.nn as nn

data_len = 1000
size = 512
X = torch.rand(data_len, 1, size, size, dtype=torch.float)
y = torch.ones((data_len, size, size), dtype=torch.int64)

class MyModule(nn.Module):
    def __init__(self):
        super().__init__()
        self.conv = nn.Conv2d(1, 20, kernel_size=1)

    def forward(self, X, **kwargs):
        return self.conv(X)

net = skorch.NeuralNet(
    MyModule(),
    criterion=torch.nn.CrossEntropyLoss,
    callbacks=[skorch.callbacks.ProgressBar()],
    batch_size=4,
    device="cuda:0",
)

net.fit(X, y)
```

Without progress bar this consumes 833 Mb of memory. With the callback enabled the consumption goes beyond 4 Gb. I observe exactly the same when running inside a notebook.

I also experimented with adding a callback which empties cache after each _batch_. Without progress bar memory consumption fluctuates in  504 .. 833 Mb range, and with progress bar the fluctuation is wild, in 580 ... 4020 Mb range.

**Comment by taketwo** [comment] 2018-08-07 15:03
Hm, I found one more interesting thing. I added the following callback to print the memory consumption (or at least PyTorch's understanding of it):

```python
class PrintMemory(skorch.callbacks.Callback):
    def on_batch_end(self, net, **kwargs):
        print(f'Allocated {torch.cuda.memory_allocated() / 1e6} Mb, cached {torch.cuda.memory_cached() / 1e6} Mb')
```

Without progress bar this reports exactly the same numbers after each batch:

```
Allocated 83.88864 Mb, cached 434.765824 Mb
```

With the progress bar (first 30 batches):

```
Allocated 83.88864 Mb, cached 350.879744 Mb
Allocated 167.775232 Mb, cached 434.765824 Mb
Allocated 251.661824 Mb, cached 518.651904 Mb
Allocated 335.548416 Mb, cached 602.537984 Mb
Allocated 419.435008 Mb, cached 686.424064 Mb
Allocated 503.3216 Mb, cached 770.310144 Mb
Allocated 587.208192 Mb, cached 854.196224 Mb
Allocated 671.094784 Mb, cached 938.082304 Mb
Allocated 83.88864 Mb, cached 938.082304 Mb
Allocated 167.775232 Mb, cached 938.082304 Mb
Allocated 251.661824 Mb, cached 938.082304 Mb
Allocated 335.548416 Mb, cached 938.082304 Mb
Allocated 419.435008 Mb, cached 938.082304 Mb
Allocated 503.3216 Mb, cached 938.082304 Mb
Allocated 587.208192 Mb, cached 938.082304 Mb
Allocated 671.094784 Mb, cached 938.082304 Mb
Allocated 754.981376 Mb, cached 1021.968384 Mb
Allocated 838.867968 Mb, cached 1105.854464 Mb
Allocated 922.75456 Mb, cached 1189.740544 Mb
Allocated 1006.641152 Mb, cached 1273.626624 Mb
Allocated 1090.527744 Mb, cached 1357.512704 Mb
Allocated 1174.414336 Mb, cached 1441.398784 Mb
Allocated 1258.300928 Mb, cached 1525.284864 Mb
Allocated 1342.18752 Mb, cached 1609.170944 Mb
Allocated 1426.074112 Mb, cached 1693.057024 Mb
Allocated 1509.960704 Mb, cached 1776.943104 Mb
Allocated 1593.847296 Mb, cached 1860.829184 Mb
Allocated 1677.733888 Mb, cached 1944.715264 Mb
Allocated 1761.62048 Mb, cached 2028.601344 Mb
Allocated 1845.507072 Mb, cached 2112.487424 Mb
```

Note that the cached size is steadily increasing. It eventually saturates at  4125 Mb, whereas the allocated size fluctuates between 83 Mb and nearly 4 Gb.

**Comment by taketwo** [comment] 2018-08-07 15:24
FWIW while stepping through the code with a debugger, I found in issue in `ProgressBar`, though it does not affect memory consumption. Here is the callback function:

```python
def on_batch_end(self, net, **kwargs):
    self.pbar.set_postfix(self._get_postfix_dict(net))
    self.pbar.update()
```

`set_postfix()` unconditionally prints the current progress bar to the output stream. `update()` also prints the current progress bar (though not every time as per `mininterval` setting). Thus we are printing new progress bar after every batch, sometimes even twice. The fix would be to pass `refresh=False` to `set_postfix()`.

**Comment by benjamin-work** [comment] 2018-08-07 15:38
Okay, when I comment out this line the leak disappears:

https://github.com/dnouri/skorch/blob/9f2258cde2c193e38c6ee1c4c8904c5a509c89ad/skorch/callbacks/logging.py#L284

I don't know what it does but I'm pretty sure it does not need to be called after each epoch. @ottonemo can you clear this up?

What I still don't get is how this can have the observed effect. `postfix` is just `{'train_loss': 4.328456401824951}`, with the value being a normal float.

**Comment by benjamin-work** [comment] 2018-08-07 15:41
> The fix would be to pass refresh=False to set_postfix()

For me, it doesn't solve the problem.

**Comment by taketwo** [comment] 2018-08-07 15:42
> For me, it doesn't solve the problem.

As I wrote, it does not solve the leak problem, only the problem of updating the progress bar too often.

> Okay, when I comment out this line the leak disappears:

Same for me!

**Comment by taketwo** [comment] 2018-08-07 15:47
And to be more specific, it's `self._get_postfix_dict(net)` that is causing problems. If I pass a fixed dict to `set_postfix()` instead, the leak is gone.

**Comment by taketwo** [comment] 2018-08-07 16:02
So this all has nothing to do with the progress bar. I nailed the problem down to accessing a non-existent key in history. Just add a callback with the following:

```python
def on_batch_end(self, net, **kwargs):
    try:
        net.history[-1, 'batches', -1, 'foobar']
    except Exception as e:
        pass
```

In the memory starts to leak. What's wrong with history remains a mystery to me.

**Comment by thomasjpfan** [comment] 2018-08-07 19:33
The following does not exhibit any gpu memory issue:

```python
def on_batch_end(self, net, **kwargs):
    try:
        net.history[-1, 'batches', -1]['train_loss']
    except Exception as e:
        pass
```

**Comment by taketwo** [comment] 2018-08-07 20:01
Yes, it only happens when accessing non-existent key. In my example `train_loss` is present, so no problem there.

**Comment by thomasjpfan** [comment] 2018-08-07 20:08
This also does not cause a gpu issue:

```python
def on_batch_end(self, net, **kwargs):
    try:
        net.history[-1, 'batches', -1]['foobar']
    except Exception as e:
        pass
```

**Comment by benjamin-work** [comment] 2018-08-08 08:42
I could narrow down the problem some more. When replacing this line

https://github.com/dnouri/skorch/blob/9f2258cde2c193e38c6ee1c4c8904c5a509c89ad/skorch/history.py#L45

to `return _missingno(None)`, the leak vanishes. Alternatively, inserting `import gc;gc.collect()` also solves the problem.

It seems that the memory leak is due to the accumulation of `_missingno` instances. How this has anything to do with cuda memory is totally beyond me. `_missingno` only has reference to `e`, the `KeyError` instance.

**Comment by benjamin-work** [comment] 2018-08-08 11:44
We could narrow down the error to pytorch itself. I created an [issue](https://github.com/pytorch/pytorch/issues/10348) there.

**Comment by ottonemo** [comment] 2018-10-16 12:55
With #312 merged this should be fixed now.

**Closed by ottonemo** 2018-10-16 12:55 UTC
